baseurl = "http://reinaldvandewalle.com/"
languageCode = "es"
title = "Reinald Arte Funcional"
theme = "reinald"

[params]
  galleriesText = "Galerías"
  aboutText = "Bio"
  contactText = "Contacto"
  footerText = "Copyright © 2016 Reinald Van De Walle, Last Updated: March 2016"
