baseurl = "http://reinaldvandewalle.com/"
languageCode = "es"
title = "Reinald Arte Funcional"
theme = "reinald"

[params]
aboutText = "Bio"
contactText = "Contacto"
footerText = "Copyright © 2018 Reinald Van De Walle, Last Updated: March 2018"
galleriesText = "Galerías"