backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "galleries" # Used in routes, e.g., /admin/collections/blog
    label: "Galleries" # Used in the UI
    folder: "content/galleries" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Gallery Items", name: "galleryitems", widget: "list", fields: [
          {label: "Item Name", name: "itemName", widget: "string"},
          {label: "Item Caption", name: "itemCaption", widget: "string"},
          {label: "Item Thumbnail", name: "itemThumb", widget: "string"},
          {label: "Item Image", name: "itemImage", widget: "string"}]}
