backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "galleries" # Used in routes, e.g., /admin/collections/blog
    label: "Galleries" # Used in the UI
    folder: "content/galleries" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Gallery Key", name: "title", widget: "string"}
      - {label: "Gallery Label", name: "label", widget: "string"}
      - {label: "Gallery Items", name: "galleryitems", widget: "list", fields: [
          {label: "Item Name", name: "itemName", widget: "string"},
          {label: "Item Caption", name: "itemCaption", widget: "markdown"},
          {label: "Item Thumbnail", name: "itemThumb", widget: "string"},
          {label: "Item Image", name: "itemImage", widget: "string"}]}

  - name: "pages"
    label: "pages"
    files:
      - file: config.toml
        label: "Site Config"
        name: config
        fields:
          - label: "Site Parameters"
            name: "params"
            widget: "object"
            fields:
              - {label: "Galleries Text", name: "galleriesText", widget: "string"}
              - {label: "About Text", name: "aboutText", widget: "string"}
              - {label: "Contact Text", name: "contactText", widget: "string"}
              - {label: "Footer Text", name: "footerText", widget: "string"}
          - {label: "Base URL", name: "baseurl", widget: "string", required: false, default: ""}
          - {label: "Language Code", name: "languageCode", widget: "string", default: "es"}
          - {label: "Title", name: "title", widget: "string", default: "Reinald Arte Funcional"}
          - {label: "Theme", name: "theme", widget: "string", default: "reinald"}
      - file: content/_index.md
        label: "Main Page"
        name: index
        fields:
          - {label: "Splash statement", name: "statement", widget: "string"}
          - {label: "Jump to galleries button text", name: "buttonText", widget: "string"}
          - {label: "Galleries heading text", name: "galleriesText", widget: "string"}
          - {label: "Gallery List", name: "gallerylist", widget: "list", fields: [
              {label: "Gallery Key", name: "galleryKey", widget: "string"},
              {label: "Gallery Name", name: "galleryName", widget: "string"},
              {label: "Gallery Image", name: "galleryImage", widget: "string"},
              {label: "Gallery Caption", name: "galleryCaption", widget: "string"}]}
          - {label: "About text", name: "aboutText", widget: "markdown"}
          - {label: "About List", name: "aboutList", widget: "list", fields: [
              {label: "About Item Title", name: "aboutItemTitle", widget: "string"},
              {label: "About Item Description", name: "aboutItemDescription", widget: "markdown"}]}
          - {label: "Contact text", name: "contactText", widget: "markdown"}
          - {label: "Contact email", name: "contactEmail", widget: "string"}
